### ISSUE TITLE
Week3 Homework

### ISSUE THREAD

**Issue by davidjwen** [happysparky/qbiodataanalysisleon#1]
Overall looks good! A few comments:
- ex 1.3 (Line 20): the following line of code can be simplified (you don't need the `[,]`): `is_row_empty <- ifelse(rowSums(na_dataframe[,]) == 0,FALSE, TRUE )` to:
```
is_row_empty <- rowSums(na_dataframe) != 0
```
- ex 1.4 (Line 45): calling `length()` on a dataframe gets you the number of columns. This is the simplest way to get the number (since true is 1 and false is 0):
```
scoredAtLeastThree <- sum(baseball$HR > 3)
```
- Nice work on the plot function by the way.

Great github name too by the way

**Comment by happysparky** [comment]
Thanks! Happysparky was the log in user for our shared accounts for monitors and various other technologies at the CS classes at my highschool so I thought it was appropriate :)
